"""add transaction pin to wallets

Revision ID: 306675e1e379
Revises: b7e164b63455
Create Date: 2026-03-20 14:32:22.309174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '306675e1e379'
down_revision: Union[str, Sequence[str], None] = 'b7e164b63455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('transaction_pin', sa.String(), nullable=True))
    op.add_column('wallets', sa.Column('pin_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('wallets', sa.Column('is_pin_locked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'is_pin_locked')
    op.drop_column('wallets', 'pin_attempts')
    op.drop_column('wallets', 'transaction_pin')
    # ### end Alembic commands ###
