"""add tier system and daily limits

Revision ID: e0acea53623f
Revises: 2efeaef06d2e
Create Date: 2026-03-19 17:02:27.794373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0acea53623f'
down_revision: Union[str, Sequence[str], None] = '2efeaef06d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tier', sa.String(length=10), nullable=False, server_default='tier1'))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('date_of_birth', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('bvn', sa.String(length=11), nullable=True))
    op.add_column('users', sa.Column('id_type', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('id_number', sa.String(length=11), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('wallets', sa.Column('daily_transfer_used', sa.Numeric(precision=20, scale=2), nullable=False, server_default='0.00'))
    op.add_column('wallets', sa.Column('daily_withdrawal_used', sa.Numeric(precision=20, scale=2), nullable=False, server_default='0.00'))
    op.add_column('wallets', sa.Column('last_daily_reset', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'last_daily_reset')
    op.drop_column('wallets', 'daily_withdrawal_used')
    op.drop_column('wallets', 'daily_transfer_used')
    op.drop_column('users', 'address')
    op.drop_column('users', 'id_number')
    op.drop_column('users', 'id_type')
    op.drop_column('users', 'bvn')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'tier')
    # ### end Alembic commands ###
